spring:
  application:
    name: timesheet

  profiles:
    active: dev

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    "org.springframework.jdbc.datasource": DEBUG
